### PR TITLE
Fix issue of creating unnecessary directory inside the update zip

### LINKED ISSUE #21: Issue while creating updates using updated pack
When creating updates using an updated pack, an unnecessary directory is added inside to the update zip.

Wrong structure - 

WSO2-CARBON-UPDATE-4.4.0-0481
├── carbon.home
**│   └── wso2is-5.2.0 <-- unnecessary directory**
│       └── repository
│           └── components
│               └── plugins
│                   └── org.wso2.carbon.identity.oauth_5.1.3.jar
├── instructions.txt
├── LICENSE.txt
├── NOT_A_CONTRIBUTION.txt
└── update-descriptor.yaml

Correct structure - 

WSO2-CARBON-UPDATE-4.4.0-0481
├── carbon.home
│   └── repository
│       └── components
│           └── plugins
│               └── org.wso2.carbon.identity.oauth_5.1.3.jar
├── instructions.txt
├── LICENSE.txt
├── NOT_A_CONTRIBUTION.txt
└── update-descriptor.yaml

### PR DESCRIPTION
**Pull request by ChanakaCooray**
In an updated pack, since the timestamp is added to the name, the name is different from the directory inside the distribution zip. So while creating an update using update-creator-tool, it will add an additional directory to the update zip because of that name difference. This PR will fix that issue.

resolves #21

### CODE REVIEW

**Comment by chamilad** [comment]
@ChanakaCooray Could you provide some examples on the values of `relativePath` that cause this issues? I didn't exactly get how this would solve the issue.

File: cmd/validate.go [hunk 1]
```diff
@@ -372,7 +372,14 @@ func readDistributionZip(filename string) (map[string]bool, error) {
...
 		logger.Trace(file.Name)
-		relativePath := strings.TrimPrefix(file.Name, productName+"/")
+
+		var relativePath string
+		if (strings.Contains(file.Name, "/")) {
+			relativePath = strings.SplitN(file.Name, "/", 2)[1]
+		} else {
+			relativePath = file.Name
+		}
+
```
Comment (chamilad) [inline cmd/validate.go]: Looks like the code is duplicated between here and `create.go/readZip()` method. Could it be refactored?

Comment (chamilad) [inline cmd/validate.go]: What I meant was the complete code segment which reads the Zip file.

**Comment by ChanakaCooray** [comment]
@chamilad uct is calling `strings.TrimPrefix(file.Name, productName + "/")` to remove the `productName` from `file.Name` to create the `relativePath`,

Example,
```
file.Name = wso2is-5.2.0/repository/tenants/
productName = wso2is-5.2.0
```
Then the relativePath would be `repository/tenants/`

But in the updated pack,

```
file.Name = wso2is-5.2.0/repository/tenants/
productName = wso2is-5.2.0.1486450987078
```
Since the productName does not matches with the file.Name prefix,  relativePath would be same as file.Name. That is the reson for including wso2is-5.2.0 directory in the update zip.

So instead of splitting string from productName, here I splitting from first '/'

File: cmd/validate.go (hunk 1 above)
Comment (ChanakaCooray) [inline cmd/validate.go]: Yes seems like we can do that. I will update the PR.

Comment (ChanakaCooray) [inline cmd/validate.go]: @chamilad I tried to refactor the code to use same util method to read zip in `validate.go` and `create.go`. But in those two classes, they are reading the zip to achieve two different goals. In `create.go`, it will read the zip and stores the files in nodes and in `validate.go` it will read the zip and store files on a string map.

Comment (chamilad) [inline cmd/validate.go]: @ChanakaCooray Approved.
