### PR TITLE
Fix issue related to archiver package upgrade

### LINKED ISSUE #2: Issue due to archiver package code change
https://github.com/mholt/archiver was changed recently. So when we use **go get** command or when we try to build it, it will show the following error.

`cmd/create.go:314: cannot call non-function archiver.Zip (type archiver.zipFormat)`

We need to change the usage of this package according to their newest documentation.

### PR DESCRIPTION
**Pull request by Shan1024**
This commit changes the archiver package usage. This is done to fix
'cannot call non-function archiver.Zip' issue which occurs due to
recent code changes in the archiver package.

Resolves #2

### CODE REVIEW

File: cmd/create.go [hunk 1]
```diff
@@ -311,7 +311,7 @@ func createUpdate(updateDirectoryPath, distributionPath string) {
 	targetDirectory = strings.Replace(targetDirectory, "/", constant.PATH_SEPARATOR, -1)
 
 	logger.Debug(fmt.Sprintf("targetDirectory: %s", targetDirectory))
-	err = archiver.Zip(updateZipName, []string{targetDirectory})
+	err = archiver.Zip.Make(updateZipName, []string{targetDirectory})
```
Comment (Niranjan-K) [inline cmd/create.go]: @Shan1024 : Can we use a release version of this (If possible)? because if we are dependent on the master, then there are chances of this happening again.

Comment (Shan1024) [inline cmd/create.go]: @Niranjan-K Currently, this is not possible using **go get** command. We will have to use a 3rd party Package Management Tool. A list of these tools are can be found in the link below.

https://github.com/golang/go/wiki/PackageManagementTools

Should we use one of those tools? WDYT?

Comment (Shan1024) [inline cmd/create.go]: Glide is seems to be a popular tool used to manage packages in go. Its better to check whether we can use this or one of the other tools mentioned in the link in the above comment for our projects.

https://github.com/Masterminds/glide

**Comment by imesh** [comment]
I'm merging this PR since the master branch is currently broken.

File: cmd/create.go (hunk 1 above)
Comment (Shan1024) [inline cmd/create.go]: @Niranjan-K Since all these are in the same repo, I created a single issue at https://github.com/wso2/wum-client/issues/155

Comment (Niranjan-K) [inline cmd/create.go]: Created an issue in this repo as well : #4

Comment (chamilad) [inline cmd/create.go]: Go has not included the version in dependency management to enforce a certain level of consistent contract. Also, if Git Work Flow is used, the `master` branch should have been the stable one while the `development` branch is the unstable one. 

Anyway, let's do a comprehensive review of the dependency managment tools and select one. I have worked with Godep and manual use of the `vendor` folder, however IMO we should completely remove from using the `go` `get` tool to manage dependencies, which with lack of version causes problems.
